### PR TITLE
Fire Button and Fireproofing tests adjusted based on new logic

### PR DESCRIPTION
**Pull request by tomasstrba**
Task/Issue URL: https://app.asana.com/0/0/1205202101916854/f
CC: @kdzwinel

Description:
Privacy reference tests adjusted according to the new Fire Button logic

Steps to test this PR:

1. Make sure tests are aligned with the new logic -> https://app.asana.com/0/0/1200195761608662/f
1. Make sure tests pass

### CODE REVIEW

**Comment by kdzwinel** [comment]
Thanks Tom! Let's add two more tests to test the code calculating the eTDL+1:
- "fireproofed.co.uk" - if eTLD+1 is calculated in a wrong way it will be "co.uk" which will fireproof incorrectly all websites under "co.uk" (e.g. example.co.uk)
- similarly with "a.github.io" and "b.github.io" are NOT the same site (eTLD+1 for "a.gihtub.io" should be "a.github.io")

**Comment by tomasstrba** [comment]
@kdzwinel, thanks for additional suggestions. I implemented new tests covering co.uk domain and github.io domain and verified they pass on macOS with the new logic.

**Review by kdzwinel — APPROVED** [review]
Tests LGTM, thanks Tom! Before you merge, can you please verify why Android tests (ask Marcos) and BSK tests are failing?

**Comment by tomasstrba** [comment]
For future reference, @marcosholgado explained to me that Android is not part of CI checks yet. I had no idea and basically merged because all checks passed here

**Pull request merged**
